apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 20Gi
